Llama-3-Instruct-8B-SimPOW-1:
  completions_kwargs:
    batch_size: 900
    do_sample: true
    max_new_tokens: 2048
    model_kwargs:
      dtype: bfloat16
      trust_remote_code: True
    model_name: RAY2L/Llama-3-Instruct-8B-SimPOW-1
    stop_token_ids:
    - 128001
    - 128009
    temperature: 0.9
    top_p: 1.0
  fn_completions: vllm_local_completions
  pretty_name: Llama-3-Instruct-8B-SimPOW-1
  prompt_template: Llama-3-Instruct-8B-SimPO/prompt.txt
