pythia-410m-deduped:
  prompt_template: "pythia-410m-deduped/prompt.txt"
  fn_completions: "huggingface_local_completions"
  completions_kwargs:
    model_name: "EleutherAI/pythia-410m-deduped"
    model_kwargs:
      torch_dtype: 'bfloat16'
    max_new_tokens: 64
    temperature: 0.7
    top_p: 1.0
    do_sample: True
  pretty_name: "pythia-410m-deduped"
  link: "https://huggingface.co/EleutherAI/pythia-410m-deduped"