pythia-410m-deduped-SimPOW-0:
  prompt_template: "pythia-410m-deduped/prompt.txt"
  fn_completions: "huggingface_local_completions"
  completions_kwargs:
    model_name: "RAY2L/pythia-410m-deduped-SimPOW-0"
    model_kwargs:
      torch_dtype: 'bfloat16'
    max_new_tokens: 64
    temperature: 0.7
    top_p: 1.0
    do_sample: True
  pretty_name: "pythia-410m-deduped-SimPOW-0"
  link: "https://huggingface.co/RAY2L/pythia-410m-deduped-SimPOW-0/tree/main/checkpoint-26"